/glg4debug/glg4param omit_muon_processes  1.0
/glg4debug/glg4param omit_hadronic_processes  1.0

/rat/db/set DETECTOR geo_file "./VUV.geo"

/run/initialize

/rat/proc count
/rat/procset update 1000

/rat/proclast outroot

/tracking/storeTrajectory 1

/generator/add combo gun2:regexfill
/generator/vtx/set opticalphoton 0.0 1.0 0.0 0.0 0.0000035497 0.0000035497
/generator/pos/set slitGenPlane #-101.6 -310.0 0.0 
#/generator/pos/set -101.6 -310.0 0.0 

/run/beamOn 100000

